version: '3'
services: 
  ng-lab:
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: . 
      dockerfile: dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    commands: ['npm','run','test']

